Date time
CS2103AUG2016-W10-C3/main pull request #22
Opened 2016-10-11 12:19 UTC by mitigator

1.Date is inside "Time" class
2.Period is "Time"
3.Currently debugging GUI test cases[null exceptions everywhere], before pushing to refactor.

2016-10-11 12:20 UTC, mitigator commented
#22

2016-10-11 14:28 UTC, mitigator commented
updated fixed test cases

2016-10-12 15:38 UTC, YesYouKenSpace requested changes
I think you need to git pull first. I foresee you will be pekchek with the amount of conflicts hahahas. Just push your working branch to remote repo. Then maybe we can work on it together? There might be changes needed in View (@MCHowl) and Edit because of this.

2016-10-12 15:38 UTC, kennethtxytqw commented on src/main/java/seedu/address/logic/parser/Parser.java
> +            		+ "(( (?<isEmailPrivate>p?)d;(?<email>[^/]+))?)"
Our regex changed a lot already in the main branch

2016-10-12 15:38 UTC, kennethtxytqw commented on src/main/java/seedu/address/logic/parser/Parser.java
> +                    matcher.group("period")==null?"23:59":matcher.group("period"),
I understand the constraint with natty. But can we still pass in an empty string, but have a layer of check for empty string before passing to natty? If empty string then don't let it be processed by natty.

2016-10-12 15:38 UTC, kennethtxytqw commented on src/main/java/seedu/address/model/task/Time.java
> +            + "\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$";
Wow I wanted to refactor this, then I don't even know where to start... hahas forget it.

2016-10-13 15:07 UTC, merged